# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cuongDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cuongDemo

end

target 'hdSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'

  # Pods for hdSDK

  target 'hdSDKTests' do
    # Pods for testing
  end

end
